# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.1
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format

  - repo: https://github.com/pycqa/flake8
    rev: '7.1.1'  # pick a git hash / tag to point to
    hooks:
      - id: flake8

  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.22.2"
    hooks:
      - id: django-upgrade
        args: [ --target-version, "4.2" ]   # Django version

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: check-symlinks

  - repo: local
    hooks:
      # https://johnnymetz.com/posts/check-django-migrations/
      - id: check-django-migrations
        name: Check django migrations
        entry: python3 manage.py makemigrations --dry-run --check
        language: system
        types: [python] # hook only runs if a python file is staged
        pass_filenames: false