# Generated by Django 4.2.4 on 2023-08-02 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_leaflet', '0002_auto_20200310_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='name',
            new_name='_name',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='name',
        ),
        migrations.AddField(
            model_name='map',
            name='location_search_term',
            field=models.CharField(
                blank=True,
                help_text=
                'Instead of coordinates you can enter the address or a search term, and Nominatim will try to look up the location. The first hit of the list will be used.',
                max_length=100,
                verbose_name='location search term',
            ),
        ),
        migrations.AddField(
            model_name='marker',
            name='_name',
            field=models.CharField(
                blank=True, max_length=100, verbose_name='name'
            ),
        ),
        migrations.AddField(
            model_name='marker',
            name='location_search_term',
            field=models.CharField(
                blank=True,
                help_text=
                'Instead of coordinates you can enter the address or a search term, and Nominatim will try to look up the location. The first hit of the list will be used.',
                max_length=100,
                verbose_name='location search term',
            ),
        ),
        migrations.AlterField(
            model_name='map',
            name='cmsplugin_ptr',
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name='%(app_label)s_%(class)s',
                serialize=False,
                to='cms.cmsplugin',
            ),
        ),
        migrations.AlterField(
            model_name='map',
            name='latitude',
            field=models.FloatField(
                blank=True, help_text='in °', verbose_name='latitude'
            ),
        ),
        migrations.AlterField(
            model_name='map',
            name='longitude',
            field=models.FloatField(
                blank=True,
                help_text=
                'in °<br>If you enter both latitude and longitude, these data won’t be overridden by a geocode lookup.',
                verbose_name='longitude in °',
            ),
        ),
        migrations.AlterField(
            model_name='marker',
            name='cmsplugin_ptr',
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name='%(app_label)s_%(class)s',
                serialize=False,
                to='cms.cmsplugin',
            ),
        ),
        migrations.AlterField(
            model_name='marker',
            name='latitude',
            field=models.FloatField(
                blank=True, help_text='in °', verbose_name='latitude'
            ),
        ),
        migrations.AlterField(
            model_name='marker',
            name='longitude',
            field=models.FloatField(
                blank=True,
                help_text=
                'in °<br>If you enter both latitude and longitude, these data won’t be overridden by a geocode lookup.',
                verbose_name='longitude in °',
            ),
        ),
    ]
