# Generated by Django 4.2.6 on 2023-10-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'djangocms_leaflet',
            '0003_rename_name_map__name_remove_marker_name_and_more'
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='set_marker',
            field=models.BooleanField(
                default=True,
                help_text='Set marker with name at the centre',
                verbose_name='set marker'
            ),
        ),
    ]
